name: Build and Deploy to Cloud Run and GKE cluster

on:
  push:
    branches:
    - master

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: demo-elanco
  GKE_CLUSTER: k8s-basic
  GKE_ZONE: us-central1-c

jobs:
  setup-build-deploy:
    name: Setup, Build,Publish and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build and push image to Google Container Registry
    - uses: actions/docker-build-push-gcr-update-gke-deployment-action@v1.4
      with:
        service_account: ${{ secrests.RUN_SA_KEY}} 
        zone: 'us-central1-c'
        project_id: ${{ secrets.RUN_PROJECT }}
        registry: 'gcr.io'
        image_name: "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
        cluster: ${{ env.GKE_CLUSTER }}
        namespace: 'default'
        deployment: 'front-end-dep'
        container: 'front-end'
